openapi: 3.0.1
info:
  title: Notes API
  description: Simple API for managing notes.
  version: "v1"
servers:
  - url: http://localhost:8080
paths:
  /notes:
    get:
      summary: Get all notes
      responses:
        '200':
          description: A list of notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      summary: Create a new note
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                note:
                  type: string
              required:
                - note
      responses:
        '201':
          description: Note created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Bad request if note is empty
  /notes/{id}:
    put:
      summary: Update an existing note
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                note:
                  type: string
              required:
                - note
      responses:
        '200':
          description: Note updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Bad request if note is empty
        '404':
          description: Not found if note does not exist
    delete:
      summary: Delete a note
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Note deleted
        '404':
          description: Not found if note does not exist
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: string
        note:
          type: string
